[ARC-1900] added Start Page Business Logic
AleksandreGalogreBaramidze/QuizApplication pull request #1
Opened 2021-11-26 11:14 UTC by AleksandreGalogreBaramidze

https://spaceneobank.atlassian.net/browse/ARC-1900

2021-11-26 12:56 UTC, AnaRusadze requested changes

2021-11-26 12:56 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/start/StartPageFragment.kt
> +            if (binding.userNameEditText.text.length < MINIMUM_PASSWORD_LENGTH){
სახელის ვალიდაციის ფუნქცია დაამატე და ვიუმოდელში გადაიტანე ჩეკი

2021-11-26 12:56 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="next_on_georgian">შემდეგი</string>
ეს ორი ნექსთის სახელი რა საჭიროა, ან ერთი დატოვე ან მეორე (ცისფერი მთების რეფერენსი ;დ)
ინგლისურად როგორც ვნახე არ გჭირდება

2021-11-26 14:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/start/StartPageFragment.kt
> +            if (binding.userNameEditText.text.length < MINIMUM_PASSWORD_LENGTH){
done

2021-11-26 14:34 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/values/strings.xml
> +    <string name="next_on_georgian">შემდეგი</string>
done

2021-11-26 14:41 UTC, GiorgiMamagulashvili16 requested changes

2021-11-26 14:41 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapplication/ui/start/StartPageViewModel.kt
> +            userPreference.currentUser(true)
with გამოიყენე

2021-11-26 14:42 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/start/StartPageViewModel.kt
> +            userPreference.currentUser(true)
done

2021-11-26 14:45 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/start/StartPageViewModel.kt
> +            userPreference.currentUser(true)
გვერძე მეჯდა და მაინც აქ დაწერა

2021-11-27 06:51 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-29 14:16 UTC, AnaRusadze approved these changes

2021-11-29 14:16 UTC, AnaRusadze requested changes

2021-11-29 14:16 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="passwordErrorMessage">სახელი უნდა აღემატებოდეს 3 სიმბოლოს</string>
სტრინგების სახელები ქვედა ტირეთი დაწერე ხოლმე

2021-11-29 14:38 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/values/strings.xml
> +    <string name="passwordErrorMessage">სახელი უნდა აღემატებოდეს 3 სიმბოლოს</string>
done

2021-12-01 11:06 UTC, AnaRusadze approved these changes

2021-12-01 11:06 UTC, merged