[ARC-1901] added Home Page and Splash Screen Business Logic
AleksandreGalogreBaramidze/QuizApplication pull request #2
Opened 2021-12-15 14:11 UTC by AleksandreGalogreBaramidze

https://spaceneobank.atlassian.net/browse/ARC-1901

2021-12-16 06:36 UTC, GiorgiMamagulashvili16 approved these changes

2021-12-16 06:36 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapplication/ui/adapters/HomeRecyclerAdapter.kt
> +        this.data = data.toMutableList()
with() :დ

2021-12-16 06:36 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapplication/ui/splashscreen/SplashFragment.kt
> +                findNavController().navigate(R.id.action_splashFragment_to_startPageFragment)
აქ შეიძლება თვითონ navigate() ში დაწერო if else ლოგიკა

2021-12-21 08:47 UTC, AnaRusadze requested changes

2021-12-21 08:47 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/splashscreen/SplashFragment.kt
> +                findNavController().navigate(R.id.action_splashFragment_to_startPageFragment)
martalia chveni gio

2021-12-21 08:47 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/splashscreen/SplashFragment.kt
> +        const val SPLASH_DELAY = 2000L
private

2021-12-21 10:18 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/adapters/HomeRecyclerAdapter.kt
> +        this.data = data.toMutableList()
done

2021-12-21 10:18 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/splashscreen/SplashFragment.kt
> +                findNavController().navigate(R.id.action_splashFragment_to_startPageFragment)
ერთხელ გაუვარდა

2021-12-21 10:18 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/splashscreen/SplashFragment.kt
> +                findNavController().navigate(R.id.action_splashFragment_to_startPageFragment)
done

2021-12-21 10:18 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/splashscreen/SplashFragment.kt
> +        const val SPLASH_DELAY = 2000L
done

2021-12-21 10:21 UTC, AnaRusadze approved these changes

2021-12-21 10:21 UTC, merged